// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKPAq7Z8ntRBo1mJcnaHHJK9Xwq5s4xJw',
    appId: '1:480568774195:web:6e9d287a8a942b5e449d46',
    messagingSenderId: '480568774195',
    projectId: 'jikah-1873c',
    authDomain: 'jikah-1873c.firebaseapp.com',
    storageBucket: 'jikah-1873c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUkZsnZ2LQCwaV9-RRw07UguvRlkZERMY',
    appId: '1:480568774195:android:bb99ab497e2770da449d46',
    messagingSenderId: '480568774195',
    projectId: 'jikah-1873c',
    storageBucket: 'jikah-1873c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1m2JEOQVZtuKwNHzO3k3y8tFk2ShqP_Q',
    appId: '1:480568774195:ios:e8ab1bc3bc243cc4449d46',
    messagingSenderId: '480568774195',
    projectId: 'jikah-1873c',
    storageBucket: 'jikah-1873c.firebasestorage.app',
    iosBundleId: 'com.example.jikah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1m2JEOQVZtuKwNHzO3k3y8tFk2ShqP_Q',
    appId: '1:480568774195:ios:e8ab1bc3bc243cc4449d46',
    messagingSenderId: '480568774195',
    projectId: 'jikah-1873c',
    storageBucket: 'jikah-1873c.firebasestorage.app',
    iosBundleId: 'com.example.jikah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKPAq7Z8ntRBo1mJcnaHHJK9Xwq5s4xJw',
    appId: '1:480568774195:web:605257bbae09c8c5449d46',
    messagingSenderId: '480568774195',
    projectId: 'jikah-1873c',
    authDomain: 'jikah-1873c.firebaseapp.com',
    storageBucket: 'jikah-1873c.firebasestorage.app',
  );
}
